### ISSUE TITLE
Missing Properties In Requests

### ISSUE THREAD

**Issue by jaetoole** [reapit/foundations#10777]
**Describe the bug**
We have a tool which gets updated properties every hour from the time the last instance started. Approx 1 week ago, we started getting an influx of tickets about missing properties.

It looks like from our logs these properties are not coming through in the requests even though they are been updated, it's like they're being missed entirely. Seems to be when properties come onto the market that it doesn't trigger the updated event is the only correlation we have so far.

**Additional context**
Hitting `/properties`, the app is NEA Sync. Could you check your side if you see that the responses you generated today/yesterday contained the following IDs?
CRO230658
SPR211279
SPR231494
WOR240114

**Comment by plittlewood-rpt** [comment]
Hi @jaetoole we don't store the response payloads only the requests that come in. I've had a look and can't see anything immediately wrong and those properties are indeed being returned. It does look like something strange has occurred on 20th Feb though. Up until then you were running your job hourly and the modifiedFrom date was incrementing as I'd expect, however since  20th Feb at 18:00 the call to the API has got stuck and is always passing 2024-02-20T17:00:17+00:00 as the modifiedFrom parameter which has meant the number of pages you're having to read is just going up and up (currently reading up to 144 pages). This would lead me to believe that your processor might be thinking it's not completing for some reason so is never incrementing the last run date. I've had a look at some internal tickets and can see that a script got run on 20th Feb to migrate pStdDesc to pLongDesc in response to a problem that had been reported with AI Descriptions in the CRM. This involved updating about 47k properties which is likely the reason for this. Have you got a timeout set on your job as it's likely this will take some time to page through (you can probably also stop requesting the pStdDesc field if it has indeed been removed altogether).

I've run a quick test using the same query string parameters as the ones you're passing on your hourly job and the properties are being returned (WOR240114 is currently being returned on page 10 for example). Can you let me know about the job timeout to see if that might be the issue?

**Comment by jaetoole** [comment]
@plittlewood-rpt perfect - we was under the impression that it wouldn't trigger a mass update event on foundations so never put any failsafes in for this as we don't need to update anyhting our side (we merge pStdDesc and the description field as one on our side) I'll manually increment the last feed which should fix it.

**Comment by jaetoole** [comment]
@plittlewood-rpt I don't see that same pattern on the requests we've sent weirdly.

Can you have a look for me and see if the modifiedFrom of this event today is correct? It should have the modified from of somewhere around `2024-02-25 17:00:08`

**Comment by plittlewood-rpt** [comment]
Hi @jaetoole - just had a look and the calls at ~9am today still have a modifiedFrom date of `2024-02-20T17:00:17+00:00` I'm afraid!

**Comment by jaetoole** [comment]
@plittlewood-rpt I've just added in some more logging but it appears that we are getting various property counts that are decrementing where we'd expect them to showing that we are infact changing the modified from date. I'll revert back at 10am when the next feed runs but i've attached the below to show the raw property counts logged from the count of all the items returned by foundations.


<img width="817" alt="image" src="https://github.com/reapit/foundations/assets/61322528/5f1f9f7d-78c5-4f5d-b9c8-28f7a4029354">

**Comment by plittlewood-rpt** [comment]
Hi @jaetoole this issue is only affecting MNS, not RYD - not sure if that might be skewing things in your logs? The MNS sync is definitely only passing that same modifiedFrom parameter. I'll send you some logs from our end separately.

**Comment by jaetoole** [comment]
Cheers @plittlewood-rpt I think we know what it is but as per our chat, I think it may be beneficial for service desk to have a way to bypass foundations events for mass updates.
