### ISSUE TITLE
App Consents - Unable to approve

### ISSUE THREAD

**Issue by s-finny** [reapit/foundations#7916]
**Describe the bug**
We have requested some permission updates for our application, the requests have gone out and one client has approved the request. Another client (Beresfords) are unable to 'accept' the permission request.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Beresfords have logged into the Dev protal as s.hubbard
2. Unable to click accept on the App Consent

**Expected behaviour**
The user should be able to accept the request

**Additional context**
This is stopping the latest release of the application, and enhancing the integration with Property Network.

**Comment by AshDeeming** [comment]
Hi @s-finny 
The user email logged-in, is was incorrect - This has been communicated via the customer CSM

**Comment by s-finny** [comment]
Hi @AshDeeming 
I have had some feedback from the user, can you help them please as they are no further forward in accepting the request.

Users email:

I think I know the issue. I don’t have a dev account in my email. Reapit don’t allow you have a Reapit log in and a dev log in on the same email address. Therefore, I use my MDs email address for the Dev portal as he doesn’t use Reapit. So its not allowing me to approve it. 

Can you change it to sb@beresfords.co.uk at all? Let me know if you can and ill ask his PA to look out for the email.

**Comment by AshDeeming** [comment]
Hi @s-finny 
From reviewing our installation details, it appears the app was installed on 16-02-2022 by the original email. 
Please confirm if this is now resolved or if the consent email needs to be re-issued?

**Comment by s-finny** [comment]
Hi @AshDeeming 

Its not been resolved, the user can not log into the Dev portal using the credentials s.hubbard@beresfords.co.uk

Can you change the approval email to sb@beresfords.co.uk?

**Comment by AshDeeming** [comment]
Hi @s-finny 
The approval email has now been sent to the requested.

**Comment by s-finny** [comment]
Hi @AshDeeming,

Ive been on a teams with the user and still no luck:

They clcik on the link and log in as sb@beresfords.co.uk and when clicking approve get this message.

![image](https://user-images.githubusercontent.com/45770940/196455134-92238800-968a-4f50-b722-23f9779607ec.png)

**Comment by AshDeeming** [comment]
Thanks for flagging @s-finny, I believe the user may have been toggled on sandbox however we'll take this as approval. 
Once the final customer has approved, I'll ensure the whole revision is approved.

**Comment by s-finny** [comment]
Hi @AshDeeming 

Mike is also having problems, he says he is not receiving the emails, I have resent it 3 times now. When he logs into the portal and go to our app it just says the app is already installed. Any ideas of where the user can go to Approve?

![image](https://user-images.githubusercontent.com/45770940/196659365-10146e85-4686-4d65-8ebb-242e5b735c8c.png)

**Comment by AshDeeming** [comment]
Thanks @s-finny 
I'll have the app approved based on agreement from the customer currently installed & review the issues with permission acceptance emails.
