### ISSUE TITLE
Client error when building via IAAS pipeline

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#9405]
Hi,

Regarding deployment on IAAS, I got this error when building:

![Screenshot 2023-07-06 082313](https://github.com/reapit/foundations/assets/94949137/cdbf2333-0613-4186-afd9-f9e9126e4647)

When clicking `LOGS UNAVAILABLE` button, a new tab popup:

![Screenshot 2023-07-06 082240](https://github.com/reapit/foundations/assets/94949137/07a3b84a-3ebd-4b9b-9ba3-81dbe4a2546f)

The local build is fine:

![Screenshot 2023-07-06 082841](https://github.com/reapit/foundations/assets/94949137/a55e7184-f637-46c4-b083-9c2d58663884)

Can someone please help investigate the issue?

Note: this happens to all of our apps (Tenancy Progression, Renewal Negotiations, and Change of Sharer)

**Comment by RLAV1** [comment]
Hey @AshDeeming Savills have confirmed this is another Urgent ticket required for Savills Go Live - can this be reviewed as soon as possible please :)

**Comment by HollyJoyPhillips** [comment]
Hi @RLAV1 & @abrahamseni, we believe this has been resolved but won't be certain until you re deploy. If you could please try and re deploy and let us know and we will monitor the logs?

**Comment by abrahamseni** [comment]
Now when I hit the deploy button, it will fail immediately.
Let me try to uninstall and install it again.

Except for this app, I can't even hit the deploy button, it is always loading, not sure why.
I try trigger it with empty commit, it also didn't work
![Screenshot 2023-07-12 015455](https://github.com/reapit/foundations/assets/94949137/e5f27142-86fd-4294-b7a1-196e3d861bb8)

![Screenshot 2023-07-12 015807](https://github.com/reapit/foundations/assets/94949137/09dd608a-5aac-4acc-9d94-e947315d2941)
![Screenshot 2023-07-12 015549](https://github.com/reapit/foundations/assets/94949137/2045eb4c-2316-43d2-8bac-4209cf49032c)
![Screenshot 2023-07-12 015616](https://github.com/reapit/foundations/assets/94949137/8f128397-7d61-422b-a4a7-7b6bc35e21a3)
![Screenshot 2023-07-12 015654](https://github.com/reapit/foundations/assets/94949137/e141ca0d-dd30-400e-a2fa-15de7bd1e4ab)
![Screenshot 2023-07-12 015735](https://github.com/reapit/foundations/assets/94949137/92826880-78ee-4fb2-b5f8-daa77d6fd352)

**Comment by abrahamseni** [comment]
@HollyJoyPhillips , I try to uninstall and install the Reapit Github apps, but it still didn't work. Fail immediately after deploy

**Comment by RLAV1** [comment]
Hey @HollyJoyPhillips are you able to reopen this ticket as the issue is still present?

**Comment by abrahamseni** [comment]
Hi @bashleigh and @HollyJoyPhillips 

We still experience an error while deploying.
It fails immediately, and when I try to create a new app, it won't connect.

I also try install and uninstall Reapit Apps in Github but still fail.

**Comment by bashleigh** [comment]
Hey Abraham, 

I found the issue with your remianing pipelines, it looks like there was an aditional issue that I missed related to the github webhook so when you reinstalled your github app to the repos, they weren't installed which is why the other repos worked (except for commit and PR deploys) and yours didn't. 
Am sorry but if you were to re-install the github app again for those repos, that should resolve your issues

**Comment by abrahamseni** [comment]
Hi @bashleigh ,

Everything is great!
Thank you for the help!
